version: "3.8"

services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - SKIP_SETCAP=true
    cap_add:
      - IPC_LOCK
    security_opt:
      - no-new-privileges:false
    networks:
      - web
    restart: unless-stopped

  buildkit:
    image: moby/buildkit
    container_name: buildkit
    privileged: true
    restart: unless-stopped
    networks:
      - web

  server:
    build: ./server
    image: depipe-server:latest
    container_name: depipe-server
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - depipe_data:/app/data
      - depipe_repos:/app/repos
    environment:
      - NODE_ENV=production
      - PORT=8000
      - BUILDKIT_HOST=docker-container://buildkit
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - REDIS_URL=redis://redis:6379
    group_add:
      - "999"
    networks:
      - web
    depends_on:
      - buildkit
      - caddy
      - vault
      - redis
    restart: unless-stopped
    stop_grace_period: 5s

  client:
    build: ./client
    image: depipe-client:latest
    container_name: depipe-client
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - server
    restart: unless-stopped
    stop_grace_period: 5s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  depipe_data:
  depipe_repos:
  redis_data:
